--- #YAML:1.0
name:               WebService-Blekko
version:            1.00_03
abstract:           access the Blekko JSON APIs
author:
    - Greg Lindahl <greg@blekko.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Data::Dumper:    0
    HTTP::Request:   0
    List::Util:      0
    LWP::UserAgent:  0
    Test::More:      0
    Time::HiRes:     0
    YAML:            0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
